[build]
  publish = "public"
  functions = "netlify/functions"

# Route nice path to the function
[[redirects]]
  from = "/api/pay"
  to = "/.netlify/functions/pay"
  status = 200
  force = true

# Security headers (optional)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=()"
